// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  /**  `ai.getConfig` */
  aiGetConfig: () => __TAURI_INVOKE<AiConfig>("ai_get_config"),
  /**  `ai.setConfig` */
  aiSetConfig: (config: AiConfig) => __TAURI_INVOKE<AiConfig>("ai_set_config", { config }),
  /**
   *  `ai.test` — proves endpoint, key and model name work *together*.
   *
   *  Deliberately does not save: pressing "测试连接" must not persist a half-typed
   *  key. The UI saves explicitly.
   */
  aiTest: (config: AiConfig) => __TAURI_INVOKE<null>("ai_test", { config }),
  /**
   *  `ai.chat` — streams an answer to [`AI_STREAM_EVENT`].
   *
   *  Returns as soon as the request is accepted; the answer arrives as a series
   *  of events and is terminated by one with `done: true`, which also carries
   *  `error` when the stream failed part way through.
   */
  aiChat: (requestId: string, messages: ChatMessage[]) =>
    __TAURI_INVOKE<null>("ai_chat", { requestId, messages }),
  /**
   *  `ai.digest` — streams a reading guide for one book.
   *
   *  The cache is consulted first, and a hit is replayed as a single delta: the
   *  panel then has exactly one code path whether or not a guide already existed.
   *  `refresh` skips the cache and writes a new one over the old.
   *
   *  Only a complete answer is cached. A stream that failed half way through is
   *  left out, so the next open regenerates instead of showing the stump forever.
   */
  aiDigest: (requestId: string, bookId: string, refresh: boolean) =>
    __TAURI_INVOKE<null>("ai_digest", { requestId, bookId, refresh }),
  /**  `annotation.create` — records one highlight and returns it. */
  annotationCreate: (
    bookId: string,
    chapterIdx: number,
    startChar: number,
    endChar: number,
    text: string,
    cfi: string | null,
    color: string | null,
    style: string | null,
  ) =>
    __TAURI_INVOKE<Annotation>("annotation_create", {
      bookId,
      chapterIdx,
      startChar,
      endChar,
      text,
      cfi,
      color,
      style,
    }),
  /**  `annotation.update` — restyles one highlight (re-colour / re-shape). */
  annotationUpdate: (id: string, color: string | null, style: string | null) =>
    __TAURI_INVOKE<Annotation>("annotation_update", { id, color, style }),
  /**
   *  `annotation.anchor` — hands a highlight the foliate CFI it was imported
   *  without. The reader calls it once it has located the highlight's text in a
   *  section, which is the only place a CFI can be minted.
   */
  annotationAnchor: (id: string, cfi: string) =>
    __TAURI_INVOKE<Annotation>("annotation_anchor", { id, cfi }),
  /**
   *  `annotation.note` — writes the reader's own note on a highlight, or clears
   *  it when `note` is absent or blank.
   */
  annotationNote: (id: string, note: string | null) =>
    __TAURI_INVOKE<Annotation>("annotation_note", { id, note }),
  /**  `annotation.list` — every highlight for a book, in reading order. */
  annotationList: (bookId: string) => __TAURI_INVOKE<Annotation[]>("annotation_list", { bookId }),
  /**  `annotation.delete` — removes one highlight. */
  annotationDelete: (id: string) => __TAURI_INVOKE<null>("annotation_delete", { id }),
  /**
   *  `annotation.delete_many` — removes a set of highlights, answering how many
   *  actually went.
   *
   *  The notes page selects across books, so the single-row command above would
   *  cost one request and one transaction per highlight. The count comes back
   *  rather than being taken on trust from the request: a selection is a snapshot
   *  of what was on screen, and a highlight deleted in the reader between the
   *  click and this call is not there to delete.
   */
  annotationDeleteMany: (ids: string[]) =>
    __TAURI_INVOKE<number>("annotation_delete_many", { ids }),
  /**  `book.list` */
  bookList: (query: BookQuery) => __TAURI_INVOKE<BookSummary[]>("book_list", { query }),
  /**  `book.get` */
  bookGet: (id: string) =>
    __TAURI_INVOKE<{
      id: string;
      title: string;
      subtitle: string | null;
      description: string | null;
      language: string | null;
      publisher: string | null;
      format: BookFormat;
      fileSize: number;
      /**  URL on the custom resource protocol, or `null` when there is no cover. */
      coverUrl: string | null;
      /**  Unix seconds. */
      addedAt: number;
      updatedAt: number;
      lastReadAt: number | null;
      /**  0..1. */
      progress: number | null;
      /**
       *  Opaque last-position anchor for engines that cannot resume from a
       *  fraction (a CFI for foliate-rendered Kindle books); `None` for every
       *  other format, which restarts from `progress` alone.
       */
      location: string | null;
      favorite: boolean;
      authors: string[];
      tags: string[];
    } | null>("book_get", { id }),
  /**  `book.stats` */
  bookStats: () => __TAURI_INVOKE<LibraryStats>("book_stats"),
  /**
   *  `book.images` — every image in the book, in reading order, with the
   *  chapter each one sits in. Powers the lightbox's book-wide browsing.
   */
  bookImages: (id: string) => __TAURI_INVOKE<BookImage[]>("book_images", { id }),
  /**
   *  `book.source_url` — the protocol URL the reader streams the source file
   *  from. Pure: the origin is a compile-time constant per platform, so this
   *  does no I/O and answers instantly.
   */
  bookSourceUrl: (id: string) => __TAURI_INVOKE<string>("book_source_url", { id }),
  /**
   *  `book.cover_save` — stores a PNG the frontend rendered for a book whose
   *  cover cannot be extracted on the Rust side (PDF first pages, drawn by
   *  pdf.js). The bytes must start with the PNG magic; anything else is a bug
   *  in the caller, not user input to decode.
   */
  bookCoverSave: (id: string, bytes: number[]) =>
    __TAURI_INVOKE<null>("book_cover_save", { id, bytes }),
  /**
   *  `book.import`
   *
   *  Takes absolute paths chosen by the native file dialog or dropped onto the
   *  window. One bad file never aborts the batch; each outcome is returned so the
   *  UI can summarise what happened.
   *
   *  `password` only matters to `.ctzx` packs. It travels as an argument rather
   *  than in a prompt callback so the whole batch runs on one blocking task.
   */
  bookImport: (paths: string[], password: string | null) =>
    __TAURI_INVOKE<ImportOutcome[]>("book_import", { paths, password }),
  /**
   *  `pack.export` — writes one book to a `.ctz` or `.ctzx` file.
   *
   *  The destination extension picks the format: `.ctzx` requires `password` and
   *  encrypts the archive with AES-256-GCM under an Argon2id key.
   */
  packExport: (id: string, path: string, password: string | null) =>
    __TAURI_INVOKE<null>("pack_export", { id, path, password }),
  /**  `book.delete` */
  bookDelete: (id: string) => __TAURI_INVOKE<null>("book_delete", { id }),
  /**  `book.setFavorite` */
  bookSetFavorite: (id: string, favorite: boolean) =>
    __TAURI_INVOKE<null>("book_set_favorite", { id, favorite }),
  /**  `bookmark.create` — pins the current position and returns it. */
  bookmarkCreate: (bookId: string, chapterIdx: number, fraction: number | null, label: string) =>
    __TAURI_INVOKE<Bookmark>("bookmark_create", { bookId, chapterIdx, fraction, label }),
  /**  `bookmark.list` — every bookmark for a book, in reading order. */
  bookmarkList: (bookId: string) => __TAURI_INVOKE<Bookmark[]>("bookmark_list", { bookId }),
  /**  `bookmark.delete` — removes one bookmark. */
  bookmarkDelete: (id: string) => __TAURI_INVOKE<null>("bookmark_delete", { id }),
  /**
   *  `clippings.import` — turns a file of highlights into highlights on the books
   *  it can match.
   *
   *  Three shapes go in and one report comes out: Kindle's `My Clippings.txt`, and
   *  the Markdown and CSV files this app exports. Which one it is is decided by
   *  [`clippings::detect`] from the file's own content, so a renamed file still
   *  reads.
   *
   *  `dry_run` walks the same path and writes nothing, which is what the dialog
   *  shows before the reader commits: the same report either way, so the numbers
   *  on the button are the numbers they get.
   *
   *  The file is read whole and then written to the database, which is seconds of
   *  work on a clipping file that has been growing for years — hence the blocking
   *  task rather than a synchronous command.
   */
  clippingsImport: (path: string, dryRun: boolean) =>
    __TAURI_INVOKE<Outcome>("clippings_import", { path, dryRun }),
  /**
   *  `dictionary.lookup` — platform dictionary, then the imported ones.
   *
   *  The answer is a tagged value rather than an error, because "no entry" and
   *  "no dictionary here" are answers: the popup falls through to AI on both and
   *  only mentions the first.
   */
  lookupDictionary: (term: string) => __TAURI_INVOKE<Lookup>("lookup_dictionary", { term }),
  /**  `dictionary.list` — every imported dictionary, in the order they were added. */
  dictionaryList: () => __TAURI_INVOKE<Dictionary[]>("dictionary_list"),
  /**
   *  `dictionary.import` — `path` is the picked `.ifo`; its siblings are read
   *  from the same directory.
   */
  dictionaryImport: (path: string) => __TAURI_INVOKE<Dictionary>("dictionary_import", { path }),
  /**  `dictionary.delete` — forgets one dictionary and removes its files. */
  dictionaryDelete: (id: string) => __TAURI_INVOKE<null>("dictionary_delete", { id }),
  /**
   *  `notes.export` — writes one book's highlights and notes to a readable file.
   *
   *  The destination extension picks the format (`.md` or `.csv`), the same
   *  contract `pack.export` follows: what the save dialog promised is what gets
   *  written. The write happens off the main thread because it reads the whole
   *  annotation list and touches the disk — small work, but the reader is waiting
   *  on a button.
   */
  notesExport: (id: string, path: string) => __TAURI_INVOKE<null>("notes_export", { id, path }),
  /**
   *  `notes.export_selection` — writes the highlights a screen is showing,
   *  across as many books as they come from.
   *
   *  Two arguments rather than one because the two answer different questions:
   *  `ids` is the set the reader narrowed to (a search, or 有笔记), and `book_ids`
   *  is the order the screen put them in, which is the shelf's. Sending only the
   *  ids would lose the order; sending only the books would lose the narrowing.
   */
  notesExportSelection: (bookIds: string[], ids: string[], path: string) =>
    __TAURI_INVOKE<null>("notes_export_selection", { bookIds, ids, path }),
  /**  `font.list` — every imported font, in the order they were added. */
  fontList: () => __TAURI_INVOKE<Font_Serialize[]>("font_list"),
  /**  `font.import` — `path` is the font file the reader picked. */
  fontImport: (path: string) => __TAURI_INVOKE<Font_Serialize>("font_import", { path }),
  /**  `font.delete` — forgets one font and removes its bytes. */
  fontDelete: (id: string) => __TAURI_INVOKE<null>("font_delete", { id }),
  /**  `graph.status` — what the panel needs to decide what to show. */
  graphStatus: (bookId: string) => __TAURI_INVOKE<GraphStatus>("graph_status", { bookId }),
  /**
   *  `graph.build` — extracts entities and relations chapter by chapter and
   *  replaces the book's graph. Progress arrives on [`GRAPH_BUILD_EVENT`].
   */
  graphBuild: (bookId: string) => __TAURI_INVOKE<number>("graph_build", { bookId }),
  /**
   *  `graph.query` — all entities when `entity` is `null`, otherwise the
   *  neighborhood of that one entity.
   */
  graphQuery: (bookId: string, entity: string | null) =>
    __TAURI_INVOKE<GraphView>("graph_query", { bookId, entity }),
  /**
   *  `lookup.translate` — one DeepL round trip, no streaming: a paragraph comes
   *  back in well under a second and the popup renders it whole. The key lives
   *  in the same settings row as the AI config; an empty key is the frontend's
   *  signal to fall back to the streaming AI translation instead.
   */
  lookupTranslate: (text: string) => __TAURI_INVOKE<Translation>("lookup_translate", { text }),
  /**
   *  `lookup.wikipedia` — best-matching article summary for a term, zh wiki
   *  first for CJK selections with the English edition as fallback.
   */
  lookupWikipedia: (term: string) => __TAURI_INVOKE<WikiSummary>("lookup_wikipedia", { term }),
  /**  `rag.status` — what the AI drawer needs to decide which controls to show. */
  ragStatus: (bookId: string) => __TAURI_INVOKE<RagStatus>("rag_status", { bookId }),
  /**  `rag.indexBook` — rebuilds the embedding index for one book. */
  ragIndexBook: (bookId: string) => __TAURI_INVOKE<number>("rag_index_book", { bookId }),
  /**
   *  `rag.chat` — retrieval-backed answer: embed the question, take the top
   *  chunks, then stream an answer that cites them.
   */
  ragChat: (requestId: string, question: string, bookId: string | null) =>
    __TAURI_INVOKE<null>("rag_chat", { requestId, question, bookId }),
  /**  `reader.toc` — chapter metadata in reading order. */
  readerToc: (bookId: string) => __TAURI_INVOKE<ChapterMeta[]>("reader_toc", { bookId }),
  /**  `reader.chapter` — the body of one chapter. */
  readerChapter: (bookId: string, idx: number) =>
    __TAURI_INVOKE<ChapterContent>("reader_chapter", { bookId, idx }),
  /**
   *  `reader.setProgress` — records a 0..1 reading position.
   *
   *  `location` is an opaque anchor for engines that cannot resume from the
   *  fraction alone (a CFI for foliate-rendered Kindle books). `None` keeps the
   *  stored anchor, so the prose path never clears a Kindle position.
   */
  readerSetProgress: (bookId: string, progress: number | null, location: string | null) =>
    __TAURI_INVOKE<null>("reader_set_progress", { bookId, progress, location }),
  /**
   *  `search.query` — chapters whose text contains `needle`, best match first.
   *
   *  Runs on a blocking task: books imported before the reader engine existed get
   *  their chapters extracted on first use, which reads the source file.
   */
  searchQuery: (needle: string, bookId: string | null, limit: number | null) =>
    __TAURI_INVOKE<SearchHit[]>("search_query", { needle, bookId, limit }),
  /**  `source.list` — every stored source, definition included. */
  sourceList: () => __TAURI_INVOKE<SourceEntry[]>("source_list"),
  /**  `source.save` — insert or update one source; returns its id. */
  sourceSave: (id: string | null, def: SourceDef) =>
    __TAURI_INVOKE<string>("source_save", { id, def }),
  /**  `source.delete` */
  sourceDelete: (id: string) => __TAURI_INVOKE<null>("source_delete", { id }),
  /**  `source.search` */
  sourceSearch: (sourceId: string, keyword: string) =>
    __TAURI_INVOKE<SourceBook[]>("source_search", { sourceId, keyword }),
  /**  `source.book` — book detail for a URL from the search results. */
  sourceBook: (sourceId: string, bookUrl: string) =>
    __TAURI_INVOKE<SourceBook>("source_book", { sourceId, bookUrl }),
  /**  `source.chapters` */
  sourceChapters: (sourceId: string, bookUrl: string) =>
    __TAURI_INVOKE<SourceChapter[]>("source_chapters", { sourceId, bookUrl }),
  /**
   *  `source.download` — walks the whole book into the library and reports
   *  progress per chapter. The command resolves only when the book is on the
   *  shelf, so the UI can navigate straight to it.
   */
  sourceDownload: (sourceId: string, bookUrl: string) =>
    __TAURI_INVOKE<Downloaded>("source_download", { sourceId, bookUrl }),
  /**  `stats.recordSession` — adds `seconds` to today's row for `book_id`. */
  statsRecordSession: (bookId: string, seconds: number) =>
    __TAURI_INVOKE<null>("stats_record_session", { bookId, seconds }),
  /**
   *  `stats.reading` — today, the last week, the lifetime total, the streak and
   *  the trailing days for the heat map.
   */
  statsReading: () => __TAURI_INVOKE<ReadingStats>("stats_reading"),
  /**  `sync.getConfig` */
  syncGetConfig: () => __TAURI_INVOKE<SyncConfig>("sync_get_config"),
  /**  `sync.setConfig` — returns the stored, normalized form. */
  syncSetConfig: (config: SyncConfig) => __TAURI_INVOKE<SyncConfig>("sync_set_config", { config }),
  /**  `sync.test` — proves the server is reachable and authorized; does not save. */
  syncTest: (config: SyncConfig) => __TAURI_INVOKE<null>("sync_test", { config }),
  /**  `sync.now` — pull, merge, apply and push; returns what each side kept. */
  syncNow: (config: SyncConfig) => __TAURI_INVOKE<SyncReport>("sync_now", { config }),
  /**  `system.info` */
  systemInfo: () => __TAURI_INVOKE<SystemInfo>("system_info"),
  /**  `tag.list` */
  tagList: () => __TAURI_INVOKE<TagSummary[]>("tag_list"),
  /**  `tag.delete` — removes one tag from every book that carries it. */
  tagDelete: (id: string) => __TAURI_INVOKE<null>("tag_delete", { id }),
  /**
   *  `book.setTags` — applies a set difference to one or more books.
   *
   *  The per-book sheet computes `add`/`remove` against what it was shown; the
   *  batch bar passes only `add`, so selecting ten books cannot clear a label
   *  the bar never knew about. One command instead of two, because the operation
   *  really is one: a difference applied to a set of books.
   */
  bookSetTags: (ids: string[], add: string[], remove: string[]) =>
    __TAURI_INVOKE<null>("book_set_tags", { ids, add, remove }),
  /**  `tts.edgeVoices` — every voice the service offers. */
  ttsEdgeVoices: () => __TAURI_INVOKE<EdgeVoice[]>("tts_edge_voices"),
  /**  `tts.edgeSpeak` — one utterance, with its word timings. */
  ttsEdgeSpeak: (text: string, voice: string, rate: number | null) =>
    __TAURI_INVOKE<EdgeClip>("tts_edge_speak", { text, voice, rate }),
};

/* Types */
/**  Where chat completions are sent and how they are signed. */
export type AiConfig = {
  /**  Origin only, e.g. `https://api.openai.com/v1`. */
  baseUrl: string;
  /**  Empty for local endpoints that need no key. */
  apiKey: string;
  model: string;
  /**  Prepended to every conversation; keeps answers in the reader's voice. */
  systemPrompt?: string;
  /**
   *  Embedding model for RAG. Empty disables library-wide retrieval; the chat
   *  assistant works without it. Same endpoint and key as chat.
   */
  embeddingModel?: string;
  /**
   *  Reranker for retrieval, Cohere-compatible `/rerank`. Empty disables the
   *  second-stage ranking. Same endpoint and key as chat.
   */
  rerankModel?: string;
  /**
   *  DeepL auth key for the selection toolbar's instant translation; `:fx`
   *  marks a free-tier key. Empty falls back to the chat model for
   *  translation.
   */
  deeplKey?: string;
};

/**  One chunk of a streamed answer. */
export type AiDelta = AiDelta_Serialize | AiDelta_Deserialize;

/**  One chunk of a streamed answer. */
export type AiDelta_Deserialize = {
  /**  Echoed back so a reopened panel can ignore a stream it no longer owns. */
  requestId: string;
  /**  Present on incremental text. */
  text: string | null;
  /**  Set on the final event; `null` while streaming. */
  done: boolean;
  /**  Provider's stop reason when it reports one. */
  finishReason: string | null;
  /**  Set only on the final event when the stream failed. */
  error: string | null;
  /**  RAG sources, present on the final event of a retrieval-backed answer. */
  citations?: RagHit[];
};

/**  One chunk of a streamed answer. */
export type AiDelta_Serialize = {
  /**  Echoed back so a reopened panel can ignore a stream it no longer owns. */
  requestId: string;
  /**  Present on incremental text. */
  text: string | null;
  /**  Set on the final event; `null` while streaming. */
  done: boolean;
  /**  Provider's stop reason when it reports one. */
  finishReason: string | null;
  /**  Set only on the final event when the stream failed. */
  error: string | null;
  /**  RAG sources, present on the final event of a retrieval-backed answer. */
  citations?: RagHit[];
};

/**  A highlight as the UI sees it. */
export type Annotation = {
  id: string;
  bookId: string;
  chapterIdx: number;
  startChar: number;
  endChar: number;
  text: string;
  /**
   *  Opaque re-anchoring key for foliate-rendered books (a CFI). `None` for
   *  every format the (chapter, offset) pair already locates.
   */
  cfi: string | null;
  /**  Highlight ink as a hex string (e.g. "#ffd12e"); `None` = legacy yellow. */
  color: string | null;
  /**
   *  How the ink paints: "highlight" (translucent wash), "underline" or
   *  "squiggly"; `None` reads as "highlight".
   */
  style: string | null;
  /**
   *  The reader's own words about this highlight. `None` = no note, which is
   *  the common case; blanks are folded to `None` on the way in, so a cleared
   *  note reads exactly like one that was never written.
   */
  note: string | null;
  createdAt: number;
};

/**  Formats the library can hold today. */
export type BookFormat =
  | "epub"
  | "pdf"
  /**  MOBI and its Kindle siblings (`.azw`, `.azw3` are the same container). */
  | "mobi"
  | "fb2"
  /**  A comic book archive: a ZIP of page images. */
  | "cbz"
  | "markdown"
  | "txt";

/**  One in-book image: the chapter it sits in and its archive entry path. */
export type BookImage = {
  chapterIdx: number;
  path: string;
};

export type BookOutcome = {
  bookId: string;
  title: string;
  total: number;
  imported: number;
  duplicates: number;
  /**  Text the book no longer contains, so nothing could be anchored. */
  unlocated: number;
};

/**  Parsed list request coming from the frontend. */
export type BookQuery = {
  filter?: LibraryFilter;
  sort?: LibrarySort;
  /**  Case-insensitive substring matched against title and author names. */
  search?: string | null;
  /**
   *  Restricts the shelf to one tag (matched case-insensitively). Orthogonal
   *  to `filter`: the tag browser is the "标签" shelf, but a future caller
   *  could ask for a tag inside 收藏 without a second query type.
   */
  tag?: string | null;
};

/**  How one book-detail call reads the metadata. */
export type BookRules = {
  title?: string;
  author?: string;
  intro?: string;
  cover?: string;
};

/**  A book as the UI sees it. */
export type BookSummary = {
  id: string;
  title: string;
  subtitle: string | null;
  description: string | null;
  language: string | null;
  publisher: string | null;
  format: BookFormat;
  fileSize: number;
  /**  URL on the custom resource protocol, or `null` when there is no cover. */
  coverUrl: string | null;
  /**  Unix seconds. */
  addedAt: number;
  updatedAt: number;
  lastReadAt: number | null;
  /**  0..1. */
  progress: number | null;
  /**
   *  Opaque last-position anchor for engines that cannot resume from a
   *  fraction (a CFI for foliate-rendered Kindle books); `None` for every
   *  other format, which restarts from `progress` alone.
   */
  location: string | null;
  favorite: boolean;
  authors: string[];
  tags: string[];
};

/**  A bookmark as the UI sees it. */
export type Bookmark = {
  id: string;
  bookId: string;
  chapterIdx: number;
  fraction: number | null;
  label: string;
  createdAt: number;
};

/**
 *  What the merge decided for one book. Struct variants so the serialized
 *  form is a flat `{ decision, title, progress }` object.
 */
export type Change =
  /**  Only the local side knew this position; it went up. */
  | { decision: "uploaded"; title: string; progress: number | null }
  /**  The remote entry was newer and has been applied to the local database. */
  | { decision: "downloaded"; title: string; progress: number | null }
  /**  The remote holds a book this device has not imported; left untouched. */
  | { decision: "remoteOnly"; title: string; progress: number | null }
  /**  Both sides agree. */
  | { decision: "unchanged"; title: string; progress: number | null };

/**  A single chapter's body, returned by the reader. */
export type ChapterContent = {
  idx: number;
  title: string;
  paragraphs: string[];
};

/**  One chapter row, ready to hand to the frontend without its body. */
export type ChapterMeta = {
  idx: number;
  title: string;
  /**  Character count of the whole chapter, used for progress mapping. */
  chars: number;
};

/**  How one chapter-list call finds chapters. */
export type ChapterRules = {
  list?: string;
  title?: string;
  url?: string;
};

/**  One turn in a conversation. `system` arrives separately, not as a message. */
export type ChatMessage = {
  role: Role;
  content: string;
};

/**
 *  How one content call yields body text: a string (split on newlines) or an
 *  array of paragraph strings.
 */
export type ContentRules = {
  paragraphs?: string;
};

/**  Reading time for one calendar day. */
export type DayTotal = {
  /**  Local day, `YYYY-MM-DD`. */
  day: string;
  seconds: number;
};

/**  One imported dictionary, as the settings document and the UI hold it. */
export type Dictionary = {
  id: string;
  name: string;
  /**
   *  Which reader to open the bundle with. Defaulted rather than required so
   *  a list written before the second format still loads.
   */
  kind?: string;
  /**  As the bundle declares it; kept for display, not trusted for sizing. */
  wordcount: number;
  addedAt: number;
};

/**
 *  The download outcome: the shelf entry that was created (or was already
 *  there, when the same bytes were downloaded before).
 */
export type Downloaded = {
  bookId: string;
  title: string;
  duplicate: boolean;
};

/**  One utterance: its audio, and where each word sits inside it. */
export type EdgeClip = {
  /**
   *  24 kHz mono MP3, base64.
   *
   *  Base64 inside the same payload as the timings rather than a raw IPC body
   *  on a second call: the two are useless apart, and one round trip per
   *  sentence is what keeps the prefetch simple.
   */
  audio: string;
  words: EdgeWord[];
};

/**  A voice the service offers. */
export type EdgeVoice = {
  /**
   *  The service's id, e.g. `zh-CN-YunjianNeural`. This is what crosses the
   *  wire on every request, and what the reader's pick is stored as.
   */
  shortName: string;
  /**  Display name, without the locale prefix and the `Neural` suffix. */
  name: string;
  locale: string;
  /**
   *  What the voice is styled for ("Novel", "News", "Dialect"). Yunjian,
   *  Yunxi, Yunxia and Yunyang are all male Mandarin voices that differ only
   *  by this, so it is the one label worth showing.
   */
  categories: string;
};

/**  One word the service reports, `at` seconds from the start of the clip. */
export type EdgeWord = {
  at: number | null;
  text: string;
};

/**  One imported font, as the settings document and the UI hold it. */
export type Font = Font_Serialize | Font_Deserialize;

/**  One imported font, as the settings document and the UI hold it. */
export type Font_Deserialize = {
  id: string;
  /**
   *  What the reader sees. Taken from the file's own name: the embedded name
   *  table would mean parsing each format's header, and the file name is what
   *  the reader picked anyway.
   */
  name: string;
  /**
   *  The stored file's name inside the fonts directory. Carried rather than
   *  derived so resolving an id to a path stays a lookup, never a scan.
   */
  file: string;
  addedAt: number;
};

/**  One imported font, as the settings document and the UI hold it. */
export type Font_Serialize = {
  id: string;
  /**
   *  What the reader sees. Taken from the file's own name: the embedded name
   *  table would mean parsing each format's header, and the file name is what
   *  the reader picked anyway.
   */
  name: string;
  /**
   *  The stored file's name inside the fonts directory. Carried rather than
   *  derived so resolving an id to a path stays a lookup, never a scan.
   */
  file: string;
  addedAt: number;
  /**
   *  Absolute URL the renderer loads the face from.
   *
   *  Written for the frontend and deliberately **not** read back: the origin
   *  is decided at compile time (`resource_origin`), and freezing a value
   *  derived from it into storage would outlive the build that produced it.
   */
  url: string;
};

/**  One extracted entity. */
export type GraphEntity = {
  name: string;
  kind: string;
  mentions: number;
};

export type GraphProgress = {
  done: number;
  total: number;
};

/**  One extracted relation, anchored to the chapter it first appeared in. */
export type GraphRelation = {
  subject: string;
  relation: string;
  object: string;
  evidence: string;
  chapterIdx: number;
};

/**  Node and edge counts plus the chat model that would do the extraction. */
export type GraphStatus = {
  entities: number;
  relations: number;
  model: string;
};

/**  What the frontend renders: all entities, or the neighborhood of one. */
export type GraphView = {
  /**  All entities (top of the list by mentions) when `entity` is `None`. */
  entities: GraphEntity[];
  /**  Both directions of one entity's relations when `entity` is set. */
  relations: GraphRelation[];
};

/**  What happened to one file in the batch. */
export type ImportOutcome =
  | { kind: "imported"; path: string; id: string; title: string }
  /**  The same bytes are already on the shelf. */
  | { kind: "duplicate"; path: string; id: string; title: string }
  | { kind: "failed"; path: string; message: string };

/**  Progress payload for [`IMPORT_PROGRESS_EVENT`]. */
export type ImportProgress = {
  done: number;
  total: number;
  path: string;
};

/**  Which shelf the user is looking at. */
export type LibraryFilter = "all" | "recent" | "favorites";

/**  Sort orders exposed by the UI. */
export type LibrarySort =
  | "recentlyAdded"
  | "recentlyRead"
  | "titleAsc"
  | "authorAsc"
  | "oldestAdded"
  | "formatAsc"
  | "sizeDesc";

/**  Aggregate counts shown above the shelf. */
export type LibraryStats = {
  total: number;
  favorites: number;
  /**  Started but not finished: has a read timestamp and is below 100%. */
  reading: number;
  finished: number;
};

/**  What a lookup turned up. */
export type Lookup =
  /**
   *  Something knew the term. `text` is the entry verbatim; `source` names the
   *  dictionary it came from, and is `None` for the platform's own — the popup
   *  only labels an answer when it has to say which one won.
   */
  | { status: "found"; text: string; source: string | null }
  /**
   *  The dictionary is there but does not carry this term. An ordinary answer,
   *  not a failure — the caller falls through to the AI explanation.
   *
   *  `allow` outside macOS, the mirror of `Unavailable` above: with no system
   *  dictionary there is nothing to be *missing* from, so only the macOS
   *  implementation ever builds this variant. It stays in the enum because the
   *  API — and the popup's fall-through — speaks all three states, and a
   *  non-macOS build used to fail on it under `-D warnings`.
   */
  | { status: "missing" }
  /**
   *  This platform ships no system dictionary.
   *
   *  `allow` rather than `expect`: on macOS this variant is genuinely never
   *  built — the platform always has a dictionary — and the test that pins the
   *  three-state contract does construct it, which would leave an `expect`
   *  unfulfilled and fail the gate.
   */
  | { status: "unavailable" };

/**
 *  What the dialog renders: before the import as a preview, after it as the
 *  receipt. Both come out of the same run.
 */
export type Outcome = {
  /**  Highlight entries in the file, notes and bookmarks excluded. */
  total: number;
  notes: number;
  bookmarks: number;
  /**  Highlights whose book is on the shelf. */
  matched: number;
  /**  Of those, the ones whose text was found in the book and anchored. */
  located: number;
  /**
   *  Highlights that were not already in the library, so a preview reports
   *  exactly what a real run writes and the confirm button can show it.
   */
  imported: number;
  /**  Already in the library from an earlier import of the same file. */
  duplicates: number;
  books: BookOutcome[];
  unknownTitles: string[];
};

/**  One retrieved chunk, handed to the frontend and to the prompt builder. */
export type RagHit = {
  bookId: string;
  bookTitle: string;
  chapterIdx: number;
  /**
   *  Offset into the chapter's joined text — the same space the reader
   *  already navigates by.
   */
  startChar: number;
  score: number | null;
  text: string;
};

export type RagProgress = {
  done: number;
  total: number;
};

/**  Index status for one book and the library at large. */
export type RagStatus = {
  /**  Chunks stored for `book_id`. */
  bookChunks: number;
  /**  Chunks stored across the whole library. */
  libraryChunks: number;
  /**  Empty when retrieval is not configured. */
  embeddingModel: string;
};

/**  Everything the stats page draws. */
export type ReadingStats = {
  /**  Today, local time. */
  todaySeconds: number;
  /**  The last seven days, today included. */
  weekSeconds: number;
  totalSeconds: number;
  /**
   *  Consecutive days with reading time ending today or yesterday. Zero on a
   *  gap: a streak that only survives until midnight would read as a bug.
   */
  streak: number;
  /**  Distinct days ever read, the honest denominator behind the total. */
  daysRead: number;
  /**
   *  The trailing `window` days, oldest first, gaps filled with zeroes so the
   *  heat map never has to do date arithmetic.
   */
  days: DayTotal[];
};

export type Role = "system" | "user" | "assistant";

/**  One place where the needle occurs. */
export type SearchHit = {
  bookId: string;
  bookTitle: string;
  chapterIdx: number;
  chapterTitle: string;
  /**
   *  Text around the match, with the match itself wrapped in `MARK_START`
   *  and `MARK_END`.
   */
  snippet: string;
  /**  Character offset of the match inside the chapter's joined text. */
  offset: number;
};

/**  How one search call finds books. */
export type SearchRules = {
  /**  Request path; `{{keyword}}` is replaced by the percent-encoded query. */
  url?: string;
  /**  Rule locating the array of result items. */
  list?: string;
  title?: string;
  author?: string;
  intro?: string;
  cover?: string;
  /**  Rule locating the book-detail URL (relative or absolute). */
  bookUrl?: string;
};

/**  A book as a search result or detail response describes it. */
export type SourceBook = {
  title: string;
  author: string;
  intro: string;
  cover: string;
  /**  Book-detail URL, absolute or relative to the source's base URL. */
  url: string;
};

/**  One chapter of a book's table of contents. */
export type SourceChapter = {
  title: string;
  /**  Absolute URL; resolved when the list is fetched. */
  url: string;
};

/**  One complete source definition, stored as JSON in the `sources` table. */
export type SourceDef = {
  name?: string;
  baseUrl?: string;
  search?: SearchRules;
  book?: BookRules;
  chapters?: ChapterRules;
  content?: ContentRules;
};

/**  One stored source, definition included so the editor can round-trip it. */
export type SourceEntry = {
  id: string;
  name: string;
  def: SourceDef;
};

export type SourceProgress = {
  done: number;
  total: number;
  /**  Title of the chapter that just finished. */
  chapter: string;
};

/**  Where the state document lives and how to sign in. */
export type SyncConfig = {
  /**  WebDAV collection, e.g. `https://dav.example.com/dav/ColorReader`. */
  url: string;
  /**  Empty means the server needs no authentication. */
  username?: string;
  password?: string;
};

/**
 *  Everything one `sync.now` did: the per-book decisions plus highlight and
 *  bookmark tallies. The latter are counts, not lists — a library can hold
 *  hundreds of highlights and listing each would drown the panel.
 */
export type SyncReport = {
  books: Change[];
  annotations: Tally;
  bookmarks: Tally;
};

/**  Runtime description of the running application. */
export type SystemInfo = {
  appName: string;
  appVersion: string;
  os: string;
  arch: string;
  /**  WebView runtime version, when it can be detected. */
  webview: string | null;
  /**  Per-user data directory (database, caches, book packs). */
  dataDir: string;
  /**  Milliseconds since process start. */
  uptimeMs: number;
};

/**  One tag and how many books carry it. */
export type TagSummary = {
  id: string;
  name: string;
  count: number;
};

/**  Counts of what a merge did to one kind of item, for the sync report. */
export type Tally = {
  uploaded: number;
  downloaded: number;
  deleted: number;
};

/**
 *  One DeepL translation: the rendered text plus what DeepL thought the
 *  source was, shown as a small tag in the popup.
 */
export type Translation = {
  text: string;
  detectedLang: string | null;
};

/**  A Wikipedia article summary, ready to render in the lookup popup. */
export type WikiSummary = {
  title: string;
  extract: string;
  thumbnail: string | null;
  pageUrl: string;
  lang: string;
};
