//! ColorReader application entry point.

mod ai;
mod commands;
mod db;
mod dictionary;
mod document;
mod error;
mod library;
mod resource;
mod state;
mod tts;

use std::fs;
use std::time::Instant;

use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::TrayIconBuilder;
use tauri::{AppHandle, Emitter, Manager};

use crate::error::AppError;
use crate::state::AppState;

/// Boot the desktop shell.
///
/// Logging goes through `tracing`; set `RUST_LOG=colorreader=debug` to raise the level.
/// Production builds default to `info`.
pub fn run() -> tauri::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("colorreader=info")),
        )
        .init();

    // The cover protocol is captured by the builder, but the library only opens
    // once setup has resolved the data directory; the registry bridges the two.
    let registry = resource::Registry::default();
    let builder = tauri::Builder::default();
    // Registered first, and that is not decoration: this plugin decides inside
    // its own setup whether this process is the one that lives. Windows and
    // Linux deliver a `colorreader://` link by starting the app *again* with
    // the URL as its only argument, so the second launch must hand its argv to
    // the instance already running and quit. The `deep-link` feature is what
    // makes that handoff speak the plugin's own event, so `AppShell` follows a
    // forwarded link and a native one through the same path. macOS never gets
    // here on a link — it delivers the URL to the running app as an event
    // instead of forking a process.
    #[cfg(desktop)]
    let builder = builder.plugin(tauri_plugin_single_instance::init(|app, argv, _cwd| {
        // Worth a line at debug level: on the platforms this runs on, "the
        // link did nothing" is otherwise indistinguishable from "the second
        // launch never reached us", and `RUST_LOG=colorreader=debug` is how
        // that gets separated on a real machine.
        tracing::debug!(?argv, "another launch handed its arguments over");
        // The link itself was dealt with above us. What is left is surfacing
        // the window: the reader clicked the link in a browser that is now in
        // front of us, and a reader that has to hunt for the window will not
        // believe the link worked. That means *showing* it, not just focusing
        // it — a window closed with the red button is hidden, not minimized,
        // and focusing a hidden window shows nobody anything.
        reveal_window(app);
    }));
    let builder = builder
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        // Answers `colorreader://book/<id>?annotation=<id>` — the links the
        // notes export writes. macOS delivers them through `RunEvent::Opened`,
        // which the plugin turns into a `deep-link://new-url` event; the shell
        // is already running by then (or was launched for it) and follows it
        // from `AppShell`. On Windows and Linux the plugin reads them off its
        // own argv at startup, and the single-instance plugin above feeds it
        // the argv of every later launch.
        .plugin(tauri_plugin_deep_link::init())
        // Auto-update. The manifest comes from GitHub Releases (`latest.json`),
        // and the artifact is verified against the minisign public key pinned in
        // `tauri.conf.json` before anything is installed. That keypair is the
        // whole trust anchor — it is generated by us and has nothing to do with
        // Apple or Microsoft platform certificates.
        .plugin(tauri_plugin_updater::Builder::new().build())
        // Installing replaces the running bundle, so the app must be able to
        // restart itself; `relaunch()` is this plugin's command, not core's.
        .plugin(tauri_plugin_process::init())
        .invoke_handler(tauri::generate_handler![
            commands::system::system_info,
            commands::webview::webview_capture_region,
            commands::book::book_list,
            commands::book::book_get,
            commands::book::book_asset,
            commands::book::book_source_file,
            commands::book::book_export,
            commands::book::book_source_url,
            commands::book::book_cover_save,
            commands::book::book_images,
            commands::book::book_stats,
            commands::book::book_import,
            commands::book::book_delete,
            commands::book::book_delete_many,
            commands::book::book_set_favorite,
            commands::book::book_set_favorite_many,
            commands::book::book_update,
            commands::book::pack_export,
            commands::reader::reader_toc,
            commands::reader::reader_chapter,
            commands::reader::reader_set_progress,
            commands::annotation::annotation_create,
            commands::annotation::annotation_update,
            commands::annotation::annotation_anchor,
            commands::annotation::annotation_note,
            commands::annotation::annotation_list,
            commands::annotation::annotation_delete,
            commands::annotation::annotation_delete_many,
            commands::backup::backup_export,
            commands::backup::backup_stage,
            commands::clippings::clippings_import,
            commands::export::notes_export,
            commands::export::notes_export_selection,
            commands::bookmark::bookmark_create,
            commands::bookmark::bookmark_list,
            commands::bookmark::bookmark_delete,
            commands::search::search_query,
            commands::ai::ai_get_config,
            commands::ai::ai_set_config,
            commands::ai::ai_test,
            commands::ai::ai_chat,
            commands::ai::ai_digest,
            commands::lookup::lookup_translate,
            commands::lookup::lookup_wikipedia,
            commands::lookup::lookup_wiktionary,
            commands::lookup::lookup_urban,
            commands::dictionary::lookup_dictionary,
            commands::dictionary::dictionary_list,
            commands::dictionary::dictionary_import,
            commands::dictionary::dictionary_delete,
            commands::font::font_list,
            commands::font::font_import,
            commands::font::font_delete,
            commands::rag::rag_status,
            commands::rag::rag_index_book,
            commands::rag::rag_chat,
            commands::graph::graph_status,
            commands::graph::graph_build,
            commands::graph::graph_query,
            commands::source::source_list,
            commands::source::source_save,
            commands::source::source_delete,
            commands::source::source_search,
            commands::source::source_book,
            commands::source::source_chapters,
            commands::source::source_download,
            commands::stats::stats_record_session,
            commands::stats::stats_reading,
            commands::stats::stats_clear,
            commands::sync::sync_get_config,
            commands::sync::sync_set_config,
            commands::sync::sync_test,
            commands::sync::sync_now,
            commands::tag::tag_list,
            commands::tag::tag_delete,
            commands::tag::book_set_tags,
            commands::tts::tts_edge_voices,
            commands::tts::tts_edge_speak,
            commands::mini_bar::mini_bar_watch,
            commands::mini_bar::mini_bar_dismiss,
            commands::mini_bar::mini_bar_reveal,
            commands::mini_bar::mini_bar_expand,
        ])
        .setup({
            let registry = registry.clone();
            move |app| {
                let data_dir = app
                    .path()
                    .app_data_dir()
                    .map_err(|err| AppError::Message(format!("resolve app data dir: {err}")))?;
                fs::create_dir_all(&data_dir)?;

                // A restore can only be swapped in here: from this point on the
                // process holds the database open, and a running process cannot
                // replace the file it already has.
                library::backup::apply_pending(&data_dir)?;

                let layout = db::Layout::create(data_dir)?;
                let library = db::Library::open(&layout.data_dir)?;
                // The fonts directory goes with it: it is the one resource the
                // protocol has to resolve itself (see `resource::Registry`).
                registry.set(library.clone(), layout.fonts_dir.clone());

                tracing::info!(path = %layout.data_dir.display(), "application data directory ready");
                app.manage(AppState { started_at: Instant::now(), layout, library });

                // Last, because it is the one piece of the shell that can be
                // built without the library: a tray that fails to appear should
                // not take the data directory down with it.
                install_tray(app)?;

                // The floating bar's state, and nothing else: its window is
                // built on demand, the first time a read-aloud session goes
                // looking for it (see `commands::mini_bar`).
                commands::mini_bar::install(app);
                Ok(())
            }
        });

    let app = resource::install(builder, registry).build(tauri::generate_context!())?;

    // The window's close button hides the app rather than quitting it.
    // Read-aloud is a session, not a page: a reader who closes the window to
    // get it out of the way has not asked for the voice to stop, and on every
    // platform this ships on, the app going away is what silences it. ⌘Q, the
    // tray's 退出 and the Dock's own quit are the ways out that do quit.
    //
    // `App::run` consumes `self` and blocks until the last window closes; it
    // does not return a `Result` in Tauri 2.x, so the only failure path is
    // during build.
    app.run(|handle, event| match event {
        tauri::RunEvent::WindowEvent {
            label,
            event: tauri::WindowEvent::CloseRequested { api, .. },
            ..
        } if label == "main" => {
            api.prevent_close();
            if let Some(window) = handle.get_webview_window("main") {
                let _ = window.hide();
            }
        }
        // macOS: the Dock icon of an app with no visible window. Hiding a
        // window is not closing it, so nothing else brings it back and without
        // this arm the app is open but unreachable.
        #[cfg(target_os = "macos")]
        tauri::RunEvent::Reopen { .. } => reveal_window(handle),
        _ => {}
    });
    Ok(())
}

/// The tray menu's own event: the controls that belong to the *session* rather
/// than to the window.
const TRAY_CONTROL_EVENT: &str = "tts://control";

/// Shows and focuses the main window, from wherever it is: hidden behind a
/// close, minimized, or buried under another app.
///
/// `pub(crate)` because the floating bar's own window is one of the ways back —
/// see `commands::mini_bar::mini_bar_reveal`.
pub(crate) fn reveal_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        let _ = window.show();
        let _ = window.unminimize();
        let _ = window.set_focus();
    }
}

/// Builds the menu-bar icon.
///
/// It carries two kinds of item, and the split is the whole reason it exists in
/// this shape. The ones that need the *window* — show it, quit — are done here.
/// The ones that need the *session* cannot be: the queue, the position and the
/// voice are frontend state, and the frontend is exactly what is invisible when
/// this menu is being used. Those are forwarded over `TRAY_CONTROL_EVENT` and
/// carried out by the player that owns the transport (`TtsPlayer`), which is
/// sitting in the shell whether or not a reader is on screen.
///
/// The menu opens on left click as well as right: on a menu-bar icon the left
/// click is the one people reach for, and everything this app can usefully do
/// with a closed window is on it.
fn install_tray(app: &tauri::App) -> tauri::Result<()> {
    let show = MenuItem::with_id(app, "show", "显示主窗口", true, None::<&str>)?;
    let toggle = MenuItem::with_id(app, "toggle", "播放 / 暂停", true, None::<&str>)?;
    let prev = MenuItem::with_id(app, "prev", "上一句", true, None::<&str>)?;
    let next = MenuItem::with_id(app, "next", "下一句", true, None::<&str>)?;
    let stop = MenuItem::with_id(app, "stop", "停止朗读", true, None::<&str>)?;
    let quit = MenuItem::with_id(app, "quit", "退出 ColorReader", true, None::<&str>)?;
    let menu = Menu::with_items(
        app,
        &[&show, &toggle, &prev, &next, &stop, &PredefinedMenuItem::separator(app)?, &quit],
    )?;

    // Shape and alpha only: macOS paints a template image in its own menu-bar
    // colour, so the glyph carries no colour of its own — it is the app icon's
    // five reading lines as a mask (`pnpm icons`).
    let icon = tauri::image::Image::from_bytes(include_bytes!("../icons/trayTemplate.png"))?;

    TrayIconBuilder::with_id("colorreader")
        .icon(icon)
        .icon_as_template(true)
        .tooltip("ColorReader")
        .menu(&menu)
        .show_menu_on_left_click(true)
        .on_menu_event(|app, event| match event.id().as_ref() {
            "show" => reveal_window(app),
            "quit" => app.exit(0),
            // Everything else is a transport name the frontend switches on.
            action => {
                let _ = app.emit(TRAY_CONTROL_EVENT, action.to_string());
            }
        })
        .build(app)?;
    Ok(())
}

/// Generates `src/lib/bindings.ts` from the command signatures.
///
/// Run with `cargo test export_bindings`; the file is committed like any other
/// generated artefact.
///
/// Dispatch deliberately stays on `tauri::generate_handler!` (see `run`):
/// `book_asset`, `book_source_file` and `webview_capture_region` return
/// `tauri::ipc::Response` — raw bytes over the binary channel — which Specta
/// cannot describe, so they are excluded here and hand-written in
/// `src/lib/ipc.ts`.
///
/// ponytail: the command list is therefore spelled out twice. That duplication
/// cannot drift silently: a command missing from `collect_commands!` stops
/// existing in the generated `commands` object, which fails `tsc`.
#[cfg(test)]
mod specta_bindings {
    use super::commands;

    #[test]
    fn export_bindings() {
        let builder = tauri_specta::Builder::<tauri::Wry>::new()
            .commands(tauri_specta::collect_commands![
                commands::ai::ai_get_config,
                commands::ai::ai_set_config,
                commands::ai::ai_test,
                commands::ai::ai_chat,
                commands::ai::ai_digest,
                commands::annotation::annotation_create,
                commands::annotation::annotation_update,
                commands::annotation::annotation_anchor,
                commands::annotation::annotation_note,
                commands::annotation::annotation_list,
                commands::annotation::annotation_delete,
                commands::annotation::annotation_delete_many,
                commands::backup::backup_export,
                commands::backup::backup_stage,
                commands::book::book_list,
                commands::book::book_get,
                commands::book::book_stats,
                commands::book::book_images,
                commands::book::book_source_url,
                commands::book::book_cover_save,
                commands::book::book_import,
                commands::book::book_export,
                commands::book::pack_export,
                commands::book::book_delete,
                commands::book::book_delete_many,
                commands::book::book_set_favorite,
                commands::book::book_set_favorite_many,
                commands::book::book_update,
                commands::bookmark::bookmark_create,
                commands::bookmark::bookmark_list,
                commands::bookmark::bookmark_delete,
                commands::clippings::clippings_import,
                commands::dictionary::lookup_dictionary,
                commands::dictionary::dictionary_list,
                commands::dictionary::dictionary_import,
                commands::dictionary::dictionary_delete,
                commands::export::notes_export,
                commands::export::notes_export_selection,
                commands::font::font_list,
                commands::font::font_import,
                commands::font::font_delete,
                commands::graph::graph_status,
                commands::graph::graph_build,
                commands::graph::graph_query,
                commands::lookup::lookup_translate,
                commands::lookup::lookup_wikipedia,
                commands::lookup::lookup_wiktionary,
                commands::lookup::lookup_urban,
                commands::rag::rag_status,
                commands::rag::rag_index_book,
                commands::rag::rag_chat,
                commands::reader::reader_toc,
                commands::reader::reader_chapter,
                commands::reader::reader_set_progress,
                commands::search::search_query,
                commands::source::source_list,
                commands::source::source_save,
                commands::source::source_delete,
                commands::source::source_search,
                commands::source::source_book,
                commands::source::source_chapters,
                commands::source::source_download,
                commands::stats::stats_record_session,
                commands::stats::stats_reading,
                commands::stats::stats_clear,
                commands::sync::sync_get_config,
                commands::sync::sync_set_config,
                commands::sync::sync_test,
                commands::sync::sync_now,
                commands::system::system_info,
                commands::tag::tag_list,
                commands::tag::tag_delete,
                commands::tag::book_set_tags,
                commands::tts::tts_edge_voices,
                commands::tts::tts_edge_speak,
                commands::mini_bar::mini_bar_watch,
                commands::mini_bar::mini_bar_dismiss,
                commands::mini_bar::mini_bar_reveal,
                commands::mini_bar::mini_bar_expand,
            ])
            // Event payloads. They never appear in a command signature, so they
            // are not reachable from `collect_commands!` and have to be named
            // here or the frontend would have to hand-write them again.
            .typ::<commands::book::ImportProgress>()
            .typ::<commands::ai::AiDelta>()
            .typ::<commands::rag::RagProgress>()
            .typ::<commands::graph::GraphProgress>()
            .typ::<commands::source::SourceProgress>()
            .error_handling(tauri_specta::ErrorHandlingMode::Throw)
            .dangerously_cast_bigints_to_number();

        builder
            .export(specta_typescript::Typescript::default(), "../src/lib/bindings.ts")
            .expect("failed to export typescript bindings");
    }
}
